require_relative 'utility.rb' 

fastlane_version "2.28.3"

desc "Runs all the tests"
lane :test do
  test_on_mac
  scan(scheme: "Tambo iOS", project: "Tambo.xcodeproj", device: "iPhone 11")
  scan(scheme: "Tambo tvOS", project: "Tambo.xcodeproj", device: "Apple TV")
end